//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldSkills2019.Database
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Assets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assets()
        {
            this.EmergencyMaintenances = new HashSet<EmergencyMaintenances>();
        }
    
        public long ID { get; set; }
        public string AssetSN { get; set; }
        public string AssetName { get; set; }
        public long DepartmentLocationID { get; set; }
        public long EmployeeID { get; set; }
        public long AssetGroupID { get; set; }
        public string Description { get; set; }
        public int NumberOfEms
        {
            get
            {
                return EmergencyMaintenances.Count;
            }
        }
        public DateTime? EMEndDateLast
        {
            get
            {
                return EmergencyMaintenances.Select(n=>n.EMEndDate).LastOrDefault();
            }
        }
        public bool EMEndDateIsNull
        {
            get
            {
                if (EMEndDateLast == null)
                    return true;
                else
                    return false;
            }
        }
        public Nullable<System.DateTime> WarrantyDate { get; set; }
    
        public virtual AssetGroups AssetGroups { get; set; }
        public virtual DepartmentLocations DepartmentLocations { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmergencyMaintenances> EmergencyMaintenances { get; set; }
    }
}
