//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldSkills2019.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Session2Entities : DbContext
    {
        public Session2Entities()
            : base("name=Session2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssetGroups> AssetGroups { get; set; }
        public virtual DbSet<Assets> Assets { get; set; }
        public virtual DbSet<ChangedParts> ChangedParts { get; set; }
        public virtual DbSet<DepartmentLocations> DepartmentLocations { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<EmergencyMaintenances> EmergencyMaintenances { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Parts> Parts { get; set; }
        public virtual DbSet<Priorities> Priorities { get; set; }
    }
}
